name: sagemaker_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - flask
  - nginx
  - zip
  - wget
  - curl
  - pip:
      - pygame==2.5.2
      - shapely==1.6.4
      - python-dateutil==2.8.2
      - Flask-Testing==0.8.1
      - setuptools==69.0.3
      - annoy==1.17.3
      - pillow==9.0.1
      - matplotlib==3.7.4
      - numpy==1.24.3
      - pandas==2.0.3
      - PyOpenGL==3.1.7
      - scipy==1.8.0
      - scikit-image==0.21.0
      - futures==3.0.5
      - boto3==1.34.12
      - minio==7.2.0
      - cryptography==41.0.7
      - kubernetes==28.1.0
      - opencv-python==4.9.0.80
      - bokeh==3.1.1
      - rl-coach-slim==1.0.0
      - retrying==1.3.4
      - eventlet==0.34.2
      - flask==3.0.0
      - gevent==23.9.1
      - gunicorn==21.2.0
      - h5py==3.10.0
      - pytest==7.4.4
      - pytest-cov==4.1.0
      - tensorflow==2.13.1
      - tensorflow-probability==0.21.0
